### HEALTH API ENDPOINT
GET http://localhost:8080/health

###SENDING WEB ANALYSING REQUEST
POST http://localhost:8080/process-web-url
Content-Type: application/json

{
    "url": "https://dashboard.socialic.app"
}
###SENDING WEB ANALYSING REQUEST HTML 4
POST http://localhost:8080/process-web-url
Content-Type: application/json

{
    "url": "http://www.w3.org/TR/html401/"
}


###SENDING WEB ANALYSING REQUEST XHTML
POST http://localhost:8080/process-web-url
Content-Type: application/json

{
    "url": "https://www.w3.org/TR/xhtml1/"
}



