// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Chinthaka D"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/process-web-url": {
            "post": {
                "description": "Analyse web url for given URL from API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Analyse Web URL",
                "parameters": [
                    {
                        "description": "Web Url Data",
                        "name": "analyser",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.WebAnalysingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.WebAnalysingResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.HeadingDetail": {
            "type": "object",
            "properties": {
                "h1": {
                    "type": "integer"
                },
                "h2": {
                    "type": "integer"
                },
                "h3": {
                    "type": "integer"
                },
                "h4": {
                    "type": "integer"
                },
                "h5": {
                    "type": "integer"
                },
                "h6": {
                    "type": "integer"
                }
            }
        },
        "models.WebAnalysingRequest": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "models.WebAnalysingResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "headings": {
                    "$ref": "#/definitions/models.HeadingDetail"
                },
                "htmlVersion": {
                    "type": "string"
                },
                "linkData": {
                    "$ref": "#/definitions/models.WebLinkDetail"
                },
                "loginFormAvailability": {
                    "type": "boolean"
                },
                "pageTitle": {
                    "type": "string"
                }
            }
        },
        "models.WebLinkDetail": {
            "type": "object",
            "properties": {
                "externalLinks": {
                    "type": "integer"
                },
                "internalLinks": {
                    "type": "integer"
                },
                "unAccessibleLinks": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Web Analyser API - Golang",
	Description:      "Web analyser API developed using Golang",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
